global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']