name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy repository to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "~/repo"

    - name: Execute commands over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/repo
          echo "Switching to super user"
          sudo su
          echo "Stopping old containers"
          docker-compose down
          echo "Starting new containers"
          WORDPRESS_DB_HOST=db \
          WORDPRESS_DB_USER=${{ secrets.WORDPRESS_DB_USER }} \
          WORDPRESS_DB_PASSWORD=${{ secrets.WORDPRESS_DB_PASSWORD }} \
          WORDPRESS_DB_NAME=${{ secrets.WORDPRESS_DB_NAME }} \
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
          FTP_PASS=${{ secrets.FTP_PASS }} \
          FTP_USER=${{ secrets.FTP_USER }} \
          docker-compose up -d --build

    - name: Stop and restart Docker containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/repo
          sudo su
          docker-compose down
          docker-compose up -d
